### ISSUE TITLE
missing dependency for FaradayMiddleware::ParseJson: cannot load such file -- json (RuntimeError)

### ISSUE THREAD

**Issue by Nakilon** [dblock/slack-ruby-client#18]
Under Amazon Linux:
```
/home/ec2-user/.gem/ruby/2.0/gems/faraday-0.9.1/lib/faraday/middleware.rb:20:in `new': missing dependency for FaradayMiddleware::ParseJson: cannot load such file -- json (RuntimeError)
        from /home/ec2-user/.gem/ruby/2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:48:in `build'
        from /home/ec2-user/.gem/ruby/2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:162:in `block in to_app'
        from /home/ec2-user/.gem/ruby/2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:162:in `each'
        from /home/ec2-user/.gem/ruby/2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:162:in `inject'
        from /home/ec2-user/.gem/ruby/2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:162:in `to_app'
        from /home/ec2-user/.gem/ruby/2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:152:in `app'
        from /home/ec2-user/.gem/ruby/2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
        from /home/ec2-user/.gem/ruby/2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
        from /home/ec2-user/.gem/ruby/2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
        from /home/ec2-user/.gem/ruby/2.0/gems/slack-ruby-client-0.3.0/lib/slack/web/faraday/request.rb:25:in `request'
        from /home/ec2-user/.gem/ruby/2.0/gems/slack-ruby-client-0.3.0/lib/slack/web/faraday/request.rb:10:in `post'
        from /home/ec2-user/.gem/ruby/2.0/gems/slack-ruby-client-0.3.0/lib/slack/web/api/endpoints/rtm.rb:19:in `rtm_start'
        from /home/ec2-user/.gem/ruby/2.0/gems/slack-ruby-client-0.3.0/lib/slack/real_time/client.rb:39:in `block in start!'
        from /home/ec2-user/.gem/ruby/2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `call'
        from /home/ec2-user/.gem/ruby/2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
        from /home/ec2-user/.gem/ruby/2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
        from /home/ec2-user/.gem/ruby/2.0/gems/slack-ruby-client-0.3.0/lib/slack/real_time/client.rb:38:in `start!'
```
Brutally fixed by adding `json` to my Gemfile. Either gem's .gemspec should be fixed or faraday.

**Comment by dblock** [comment]
Probably gemspec, would take a PR.

**Comment by dblock** [comment]
Added via https://github.com/dblock/slack-ruby-client/commit/33562f9ff755d59a3b1bcc94b9e553747b91609d
