### ISSUE TITLE
Ruby 2.0 + celluloid-io: No live threads left. Deadlock?

### ISSUE THREAD

**Issue by dblock** [dblock/slack-ruby-client#44]
https://travis-ci.org/dblock/slack-ruby-client/jobs/101093592

```
Failures:
  1) integration test gets hello
     Failure/Error: socket.start_async { run_loop(socket, &block) }
     
     fatal:
       No live threads left. Deadlock?
     # ./vendor/bundle/ruby/2.0.0/gems/celluloid-0.17.2/lib/celluloid/mailbox.rb:63:in `block in check'
     # ./vendor/bundle/ruby/2.0.0/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'
     # ./vendor/bundle/ruby/2.0.0/gems/celluloid-0.17.2/lib/celluloid/mailbox.rb:58:in `check'
     # ./vendor/bundle/ruby/2.0.0/gems/celluloid-0.17.2/lib/celluloid/mailbox.rb:77:in `block in receive'
     # ./vendor/bundle/ruby/2.0.0/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'
     # ./vendor/bundle/ruby/2.0.0/gems/celluloid-0.17.2/lib/celluloid/mailbox.rb:76:in `receive'
     # ./vendor/bundle/ruby/2.0.0/gems/celluloid-0.17.2/lib/celluloid/call/sync.rb:50:in `wait'
     # ./vendor/bundle/ruby/2.0.0/gems/celluloid-0.17.2/lib/celluloid.rb:141:in `suspend'
     # ./vendor/bundle/ruby/2.0.0/gems/celluloid-0.17.2/lib/celluloid/call/sync.rb:41:in `response'
     # ./vendor/bundle/ruby/2.0.0/gems/celluloid-0.17.2/lib/celluloid/call/sync.rb:45:in `value'
     # ./vendor/bundle/ruby/2.0.0/gems/celluloid-0.17.2/lib/celluloid/proxy/sync.rb:38:in `method_missing'
     # ./lib/slack/real_time/client.rb:47:in `start_async'
     # ./spec/integration/integration_spec.rb:22:in `block (2 levels) in <top (required)>'
     # ./spec/integration/integration_spec.rb:44:in `start_server'
     # ./spec/integration/integration_spec.rb:93:in `block (2 levels) in <top (required)>'
     # ./spec/integration/integration_spec.rb:6:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.0.0/gems/vcr-3.0.1/lib/vcr.rb:244:in `turned_off'
     # ./spec/integration/integration_spec.rb:6:in `block (2 levels) in <top (required)>'
Finished in 6.82 seconds (files took 0.5859 seconds to load)
95 examples, 1 failure, 2 pending
```

**Comment by dblock** [comment]
Allowing to fail in https://github.com/dblock/slack-ruby-client/commit/4d6b895d87f011c87236a6da71fd6d84478ece50.

**Comment by dblock** [comment]
This was definitely fixed.
